#!/usr/bin/with-contenv bash

# make our folders
mkdir -p \
	$MEDIAWIKI_PATH \
	/config/{log/mediawiki,log/lua,nginx,php} \
	/assets/resources

# copy mediawiki files
if [ ! -e $MEDIAWIKI_PATH/index.php ]
	then
		echo 'installing mediawiki...'
		cp -r $MEDIAWIKI_STORAGE_PATH/. $MEDIAWIKI_PATH
fi

# copy config files
echo 'copying config files...'
# nginx
[[ ! -f /config/nginx/nginx.conf ]] && \
	cp /defaults/nginx/wiki-nginx.conf /config/nginx/nginx.conf && \
	echo 'default nginx.conf copied'
# php
[[ ! -f /config/php/php-local.ini ]] && \
	cp /defaults/php/php.ini /config/php/php-local.ini && \
	echo 'default php.ini copied'
# php-fpm
[[ ! -f /config/php/www2.conf ]] && \
	cp /defaults/php/php-fpm.conf /config/php/www2.conf && \
	echo 'default php-fpm.conf copied'

# set set execute permissions for mediawiki extentions
chmod a+x $MEDIAWIKI_PATH/extensions/SyntaxHighlight_GeSHi/pygments/pygmentize
chmod a+x $MEDIAWIKI_PATH/extensions/Scribunto/includes/engines/LuaStandalone/binaries/lua5_1_5_linux_64_generic/lua

# run composer for TemplateStyles if needed
if [ ! -d $MEDIAWIKI_PATH/extensions/TemplateStyles/vendor ]
	then
		cd $MEDIAWIKI_PATH/extensions/TemplateStyles
		composer install --no-dev
		chown -R abc:abc $MEDIAWIKI_PATH/extensions/TemplateStyles
fi

# set permissions for mediawiki default directory for file uploads
chmod -R a=rwx $MEDIAWIKI_PATH/images

# set ownership and permissions for mediawiki to use docker volume /assets directory for file uploads
chown -R abc:abc /assets
chmod -R a=rwx /assets


